import eventique from '../assets/Eventique_project.png';
import car_accident from '../assets/us_car_accident.png';
import natours from '../assets/Natours.png';

export const SKILLS = [
  {
    name: 'Web Dev',
    percent: '90',
  },
  {
    name: 'machine Learning',
    percent: '80',
  },
  {
    name: 'Data Analytics',
    percent: '75',
  },
  {
    name: 'REST API',
    percent: '85',
  },
  {
    name: 'Databases',
    percent: '80',
  },
  {
    name: 'java',
    percent: '90',
  },
  {
    name: 'python',
    percent: '85',
  },
  {
    name: 'javascript',
    percent: '80',
  },
  {
    name: 'nodejs',
    percent: '80',
  },
  {
    name: 'expressjs',
    percent: '85',
  },
  {
    name: 'reactjs',
    percent: '75',
  },
  {
    name: 'tailwindCSS',
    percent: '75',
  },
  {
    name: 'SQL',
    percent: '80',
  },
  {
    name: 'mySql',
    percent: '90',
  },
  {
    name: 'mongoDB',
    percent: '85',
  },
  {
    name: 'AWS(S3,lambda)',
    percent: '80',
  },
];

export const EXPERIENCES = [
  {
    year: 'Aug 2024 - Present',
    role: 'Software Engineer Intern',
    company: 'Copart Inc.',
    location: 'Dallas, TX',
    description: `Working on B2B seller integrations with majority of my work revolving around building 
    APIs, extracting insights from metrics to understand peak times, expected range of interaction etc,
    optimize DB retrieval time and others to mention a few `,
    technologies: [
      'Spring Boot',
      'Spring Data JPA',
      'Postgres/MariaDB',
      'Java',
      'REST API'
    ]
  },
  {
    year: 'Oct 2022 - Aug 2023',
    role: 'Software Engineer',
    company: 'Opentext Technologies',
    location: 'India',
    description: `Enhanced Content Hub for Publishers - a distributed web application by fixing 200+ bugs & adding 15+ new features over 2 years, 
    contributing towards 133% revenue bump. Added ability to import assets from multiple vendors using Java, Javascript and third-party APIs, 
    improving customer satisfaction by 15% (based on issue's priority).`,
    technologies: [
      'Javascript',
      'Java',
      'Solr',
      'AWS',
      'HTML/CSS',
      'Shell scripting',
    ],
  },
  {
    year: 'Jan 2021 - Sept 2022',
    role: 'Associate Software engineer',
    company: 'Opentext Technologies',
    location: 'India',
    description: `Worked closely with security and testing teams to ensure successful product release & documentation.
    Resolved 30+ security vulnerabilities and led end-to-end implementation of password encryption feature using Bash and Java, 
    strengthening password security by 70%. `,
    technologies: ['Javascript', 'Java', 'HTML/CSS', 'Shell scripting'],
  },
  {
    year: 'Oct 2020 - Dec 2020',
    role: 'Software Engineer Intern',
    company: 'Opentext Technologies',
    location: 'India',
    description: `Built a Java solution to parse an XML files and store relevant data as CSV, automating ~80% of the process.`,
    technologies: ['Java'],
  },
];

export const PROJECTS = [
  {
    title: 'Eventique - AI enhanced event planning',
    image: eventique,
    gitlink: `https://github.com/Govind-Asawa/eventique`,
    description: `A full-stack web application that leverages Large Language model (LLM) service to generate plans for an event. Integrated calendar to visualize user's tasks for an event generated by LLM.`,
    technologies: [
      'React.js',
      'tailwindCSS',
      'Django',
      'Gemini-pro',
      'postgreSql',
      'GCP',
      'CI/CD',
    ],
  },
  {
    title: 'US car accidents',
    image: car_accident,
    gitlink: `https://github.com/Govind-Asawa/US_Car_Accidents`,
    description:
      'Churned 7.7 million records, achieving 87% accuracy in predicting the severity level of car accidents in the USA by analyzing various factors contributing to the accidents, such as weather conditions, road features (like road crossings, junctions, signals), time and location, etc.',
    technologies: ['python', 'Data Analysis', 'Machine Learning'],
  },
  {
    title: 'Natours - Book your tour',
    image: natours,
    gitlink: `https://github.com/Govind-Asawa/natours-app`,
    description:
      'A Web-app for users to browse through available tour packages, view and book tours using secure payment method.',
    technologies: [
      'Node.js',
      'express.js',
      'HTML',
      'CSS',
      'javascript',
      'pug',
      'MongoDB',
    ],
  },
];
